### ISSUE TITLE
Add the following xscreensaver to the deepin collection !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-screensaver#2]
@zccrs ... great work on the deepin-screensaver ...

from the implementation i just couldn't tell that its based off `xscreensaver` ... nicely redesigned and integrated into deepin's eye candy UI ...

Please find some of the xscreensaver collection which i feel will go well with deepin's glassy minimalistic look and feel ...

List of Screensaver to be added to the current collection ...

**WhirlWindWarp
Wormhole
XMatrix
Rocks
Pyro
GLMatrix
FluidBalls
Flow
Fiberlamp**

I previewed them all from https://www.jwz.org/xscreensaver/screenshots/ ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
