### ISSUE TITLE
Deepin implementation equivalent of this xscreensaver option ? If not ... a feature request of the same !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-screensaver#3]
Source : https://www.jwz.org/xscreensaver/faq.html#mpeg

> How do I make xscreensaver play a video clip?
> To play MP4, MPEG, QuickTime, FLV and AVI videos:
> 
> Install mpv and add something like the following to the `programs' preference in your .xscreensaver file:
> 
>      "My Movie"  mpv --really-quiet --no-audio --fs --loop=inf  \
>                      --no-stop-screensaver                      \
>                      --wid=$XSCREENSAVER_WINDOW                 \
>                      $HOME/movies/poop.mp4                    \n\
> Duplicate those lines for each other movie you would like to play.
> It's also possible to encapsulate the above into a single shell script which would pick a movie file at random from a directory and play that. Several people have written such things; Google it.
> 
> To play SWF Flash animations:
> 
> Macromedia's stand-alone Flash player has xscreensaver support, as of version 6.0.79 and later. To use it, put a line like this in the `programs' preference in your .xscreensaver file:
> 
>      "My Flash"   gflashplayer -root $HOME/movies/my_flash.swf  \n\
> To play anything else:
> 
> Beats me.

Do we have a way to use mp4 files as xscreensaver does ?
If so can you please provide the procedure to do so ?

If not ... can you incorporate this option into deepin's implementation of xscreensaver ... as a feature request ?

thanks.

**Comment by felixonmars** [comment]
I believe it's just using resources of xscreensaver. You may want to look up https://github.com/zccrs/screensaver-pp as an example of customized deepin-screensaver resource.

**Comment by aiamuzz** [comment]
> I believe it's just using resources of xscreensaver. You may want to look up https://github.com/zccrs/screensaver-pp as an example of customized deepin-screensaver resource.

actually i have a gif animation which i want to use as screensaver ... hence the question on the .swf(i can easily convert my gif animation to a swf file) support similar to xscreensaver ...

I would just like to have an easy way to do so ...

@zccrs, @felixonmars  ... can you please look into such a possibility ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
