### ISSUE TITLE
Arch+dde，no deepinscreensaver

### ISSUE THREAD

**Issue by xiaoc-arch** [linuxdeepin/deepin-screensaver#4]
there is no deepin-screensaver in archLinux

**Comment by felixonmars** [comment]
Package uploaded now. Please try to update and it should be installed automatically (via dependency of deepin-file-manager).

**Comment by xiaoc-arch** [comment]
i want to learn how to make xxx.deb to arch package,is there any examples?

**Comment by felixonmars** [comment]
No that's the wrong way, please make proper packages instead of converting.

**Comment by xiaoc-arch** [comment]
If i use the source code (for example linuxdeepin project)to makepkg,is there any examples,i have read archwiki,however,i do not know how to makepkg

**Comment by felixonmars** [comment]
You can look up for a package on www.archlinux.org and click on "Source Files" link on the right. For more info ArchWiki would be a good start.
