### ISSUE TITLE
Feature Request/Enhancement : Can a mouse hover event on each screensaver film strip reveal the name of the Screensaver ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-screensaver#5]
Hi,

Wouldn't it be great to be able to know the names of the various screensavers in the collection ?

I was hoping mouse hover event(popup) with then name of that screensaver would be a nice way for users to know which screensaver they have chosen to run on their system !!!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
