### ISSUE TITLE
Adding screensaver thumbnail ... for other screensavers from the xscreensaver collection !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-screensaver#6]
Hi,

I just downloaded a few more screensavers from the xscreensaver collection and copied it to the deepin-screensaver directory ... the screensaver are being picked up in the screensaver setting but the they do not have a cover image(preview thumbnail) to go with it ... i can find only blank spaces for the newly added screensavers ... clicking on them gives the preview and we can apply it ... 

I don't know how i can add the thumbnail to the settings ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
